### ISSUE TITLE
No recaptcha pop up

### ISSUE THREAD

**Issue by RafikFarhad** [lightoj-dev/bugs-and-features#1]
While trying to login,
recaptcha do not prompt and submit gets error (Screenshot attached).
<img width="548" alt="Screenshot 2020-10-23 at 1 06 23 PM" src="https://user-images.githubusercontent.com/15923187/96967080-bd17d000-1530-11eb-917f-9da43558f338.png">

**Comment by MKGAURAB** [comment]
I found the issue only using with a mobile browser / webview.

**Comment by mostasim** [comment]
Same issue on my Browser.
Device: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36

**Comment by faiyaz26** [comment]
Should be fixed now.
