### ISSUE TITLE
Institution add Request [Barishal Zilla School]

### ISSUE THREAD

**Issue by Dhoomketoo** [lightoj-dev/bugs-and-features#100]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Barishal Zilla School
2. Website: https://www.facebook.com/Barishal-Zilla-School-Online-Page-112665373865293
3. Logo Url: https://www.facebook.com/Barishal-Zilla-School-Online-Page-112665373865293
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/bzs-bd
