### ISSUE TITLE
'Create new contest' pop-up window texts are invisible at dark mode

### ISSUE THREAD

**Issue by rahathossain690** [lightoj-dev/bugs-and-features#101]
'Create new contest' popup window texts are invisible while browsing in dark mode

1. Go to home page
2. Click on upper right profile section
3. Turn on the dark mode
4. Go to 'Author dashboard'
5. Click on 'contests' in right section
6. Click 'create new contest'

Expected behavior: Text to be visible

Screen shot:
![](https://i.imgur.com/VLItiFp.png)

**Browser information (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium
 - Version: 91.0.4472.101

**Comment by jan876** [comment]
This is fixed. Thanks for reporting.
