### ISSUE TITLE
No sorting option

### ISSUE THREAD

**Issue by hemel18681** [lightoj-dev/bugs-and-features#102]
There is no sorting option in https://lightoj.com/problems/category/dp. Previously sorting option was there and it is very helpful for the newly programmer to approach in the program form easy to hard. Thank you.
![hudai2](https://user-images.githubusercontent.com/46155472/127773358-f3135eb3-04f4-4540-a9f5-11409bcf1c5e.jpg)

**Comment by jan876** [comment]
Fixed. Thanks for reporting.
