### ISSUE TITLE
Unpredictable verdict for Java code [ LOJ 1082 - Array Queries ]

### ISSUE THREAD

**Issue by showrav-ansary** [lightoj-dev/bugs-and-features#103]
1. Problem Link: [LOJ 1082 - Array Queries](https://lightoj.com/problem/array-queries).
2. Your concern, describe the issue: Unpredictable verdict for `Java` submissions `2135085 ` and `2135084`. Both are the same code and implementation. Same for `2135009` vs `2135012`
3. Your code or submission link: `accepted` - [2135084](https://lightoj.com/submission/2135084), [2135009](https://lightoj.com/submission/2135009) ; `MLE` - [2135085](https://lightoj.com/submission/2135085) , [2135012](https://lightoj.com/submission/2135012)
4. Test case content: `b.in`.

P.S. : Custom `Reader` class implemented in submission [2135110](https://lightoj.com/submission/2135110) works perfectly but the `Scanner in = new Scanner(new BufferedReader(new InputStreamReader(System.in)));` is much popular due to it being preached in Google kickstart events.

Handicapping the `128 MB` limit to `64 MB` will make people realize to go for a custom made class as it is known simultaneous `I/O` for `Scanner(BufferedReader( InputStreamReader(System.in)))` will require to take the inputs at first then print out later, which does justify the `128 MB` limit as there will be excess memory usage to store the `output` somewhere else until there is no input left but it is insufficient in this case. Also, it raises the time complexity. While using the custom `Reader` class requires no such extra memory, `64 MB` cap is sufficient. The logical implementation except the `I/O` in both the cases is same.

**Comment by faiyaz26** [comment]
@jan876 vai, could you look into it?

**Comment by jan876** [comment]
Updated the memory limit. Should be fixed now.
