### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by The1one1** [lightoj-dev/bugs-and-features#104]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Indian Institute Of Information Technology, Lucknow
2. Website:  https://iiitl.ac.in/
3. Logo Url: https://iiitl.ac.in/wp-content/uploads/2019/10/Final_Logo_IIITL.png
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/iiitl-in
