### ISSUE TITLE
Problem statement correction for problem 1071 - Baker Vai

### ISSUE THREAD

**Issue by smhimran** [lightoj-dev/bugs-and-features#107]
In the statement of **LOJ-1071 Baker Vai**, there are some extra asterisks that may be confusing.  Probably it was a mistake from writing the statement in markdown?
![LOJ-1071](https://i.ibb.co/bXNMxHF/loj-baker-vai-bug.png)

**Comment by faiyaz26** [comment]
Thanks for reporting it, its fixed.
