### ISSUE TITLE
Institution add Request [Macquarie University]

### ISSUE THREAD

**Issue by maacpiash** [lightoj-dev/bugs-and-features#108]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Macquarie University
2. Website: [www.mq.edu.au](https://www.mq.edu.au/)
3. Logo Url: [The relevant page on the official website](https://mq.edu.au/about_us/offices_and_units/marketing/our_shared_identity_project/macquarie_university_logo/)
4. Country: Australia

**Comment by jan876** [comment]
https://lightoj.com/institutions/mq-au
