### ISSUE TITLE
Institution add request [Saidpur Govt. Science College]

### ISSUE THREAD

**Issue by Shihab-Sharar** [lightoj-dev/bugs-and-features#109]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Saidpur Government Science College
2. Website: https://sgtc.gov.bd/
3. Facebook: https://www.facebook.com/sgtc.edu.bd/
4. Logo Url: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.facebook.com%2Fsgtc.edu.bd%2Fphotos%2F&psig=AOvVaw2-XxTEvWYd3069VEeLnEWR&ust=1632911159372000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCIDM76S6ofMCFQAAAAAdAAAAABAD
5. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/sgtc-bd
