### ISSUE TITLE
Institution add Request [St. Joseph's Institute of Technology]

### ISSUE THREAD

**Issue by GRajin** [lightoj-dev/bugs-and-features#110]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: St. Joseph's Institute of Technology
2. Website: https://www.stjosephstechnology.ac.in/web/index.html
3. Logo Url: https://www.stjosephstechnology.ac.in/web/img/logo-new1.png
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/stjoseph-in
