### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by ANKIT-CH** [lightoj-dev/bugs-and-features#111]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Indian Institute of Information Technology, Una
2. Website: http://www.iiitu.ac.in/
3. Logo Url: http://www.iiitu.ac.in/images/oie_18559205hDZHYdK.gif
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/iiitu-in
