### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by Sayem15** [lightoj-dev/bugs-and-features#114]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Noakhali Zilla School
2. Website: http://www.nzs.edu.bd/
3. Logo Url: http://automation.sib.gov.bd/monogram/107540.png
4. Country: Bangladesh

**Comment by nomandhoni-cs** [comment]
Institution Name: Sonargaon Government College
    Website: http://www.nubd.info/college/college.php?code=5605
    Logo Url: http://www.nubd.info/college/uploads/5605_logo.jpg
    Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/nzs-bd
