### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by samatovich** [lightoj-dev/bugs-and-features#117]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: "Kut Bilim" educational complex
2. Website: http://kutbilim-otk.edupage.org/
3. Logo Url: http://gg.gg/kutbilim_logo
4. Country: Kyrgyzstan

**Comment by jan876** [comment]
https://lightoj.com/institutions/kutbilim-kg
