### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by k-rishabh6172** [lightoj-dev/bugs-and-features#118]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: IIIT Naya Raipur
2. Website: https://www.iiitnr.ac.in/
3. Logo Url: https://www.iiitnr.ac.in/content/significance-and-usage-institute-logo
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/iiitnr-in
