### ISSUE TITLE
Test case issue [Brush IV]

### ISSUE THREAD

**Issue by davidmontero123** [lightoj-dev/bugs-and-features#119]
Please provide the information below:

1. Problem Link: [https://lightoj.com/problem/brush-4](url)
2. Your concern, describe the issue: I'm writing a solution in O(2^N*N^2) but still getting TLE, I think my solution should pass the test cases due to the editorial solution has same overall complexity
3. Your code or submission link: [https://lightoj.com/submission/2216746](url)
4. Test case content: test cases are hidden for me

**Comment by faiyaz26** [comment]
Hello,
It seems you are getting TLE, which is common if you don't put correct break conditions. I can see many C++ solutions getting accepted, so I believe we don't have any issues on our side. Its better if you try the test cases from here: https://www.udebug.com/LOJ/1018 and see if those cases are working for you.  I am closing the issue as we don't see any issues on the test case and time limit.
