### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by anshitmishraa** [lightoj-dev/bugs-and-features#120]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Lovely Professional University
2. Website: https://www.lpu.in/
3. Logo Url: https://www.lpu.in/images/logo/logo.svg
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/lpu-in
