### ISSUE TITLE
Test case issue [IP Checking]

### ISSUE THREAD

**Issue by Taalpatar-Shepai** [lightoj-dev/bugs-and-features#121]
Please provide the information below:

1. Problem Link:https://lightoj.com/problem/ip-checking
2. Your concern, describe the issue:
I often use a technique for faster i/o operation. basically this two-line beginning of my main function.
 #define unsyncIO    		ios_base::sync_with_stdio(0); cin.tie(0)
in this problem, my code gets WA if I use this technique and if I don't use it Accepted. 
 
3. Your code or submission link: check these two submissions https://lightoj.com/submission/2221768
https://lightoj.com/submission/2221769

4. Test case content:

**Comment by faiyaz26** [comment]
With that optimization you shouldn't mix cin cout with scanf and printf

https://www.google.com/amp/s/www.geeksforgeeks.org/cincout-vs-scanfprintf/amp/

```
Like with all things, there is a caveat here. With synchronization turned off, using cin and scanf() together will result in an undefined mess.
```
