### ISSUE TITLE
Institution add Request [IIT Gandhinagar]

### ISSUE THREAD

**Issue by sanskarfc** [lightoj-dev/bugs-and-features#123]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: IIT Gandhinagar
2. Website: https://iitgn.ac.in/
3. Logo Url: https://drive.google.com/file/d/0BxhtIGw1kRnzRG1kQUxJMFFycVh1QTNQMDl6VWEwSFRjWWlN/view?resourcekey=0-tXpz6JliTzT4Ls0hvs3W_Q
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/iitgn-in
