### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by anmit007** [lightoj-dev/bugs-and-features#124]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: IIIT Bh
2. Website: https://www.iiit-bh.ac.in
3. Logo Url: https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FInternational_Institute_of_Information_Technology%2C_Bhubaneswar&psig=AOvVaw3Gi_h_TlMVoPFTAg6bPeTd&ust=1641361887371000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCLjw39Ozl_UCFQAAAAAdAAAAABAD
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/iiitbh-in
