### ISSUE TITLE
Institution add Request [Information Technology University]

### ISSUE THREAD

**Issue by bsce21017** [lightoj-dev/bugs-and-features#125]
1. Institution Name: Information Technology University
2. Website: https://itu.edu.pk/
3. Logo Url: ![Information_Technology_University](https://user-images.githubusercontent.com/91457593/150662742-e8c26cf1-e300-486e-bbd0-8ba90c18b642.png)
Original Link: https://en.wikipedia.org/wiki/Information_Technology_University#/media/File:Information_Technology_University.png 
4. Country: Pakistan

**Comment by jan876** [comment]
https://lightoj.com/institutions/itu-pk

https://lightoj.com/institutions/ualberta-ca
