### ISSUE TITLE
Institution add Request [Gurukul Kangri Vishwavidyalaya]

### ISSUE THREAD

**Issue by Machiorpolly** [lightoj-dev/bugs-and-features#126]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Gurukul Kangri(Deemed to be University)
2. Website: https://www.gkv.ac.in/
3. Logo Url: https://en.wikipedia.org/wiki/File:Gurukul_Kangri_Vishwavidyalaya_logo.jpg
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/gkv-in
