### ISSUE TITLE
how to create a team

### ISSUE THREAD

**Issue by lieweden** [lightoj-dev/bugs-and-features#127]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by faiyaz26** [comment]
Hello,
Thanks for creating the issue.

Currently, we haven't made the team creation a public thing, it's only done by the admins.

If you want to host a team (3 - 5 members per team) contest, you need to have a collaboration agreement with LightOJ
