### ISSUE TITLE
Institution add Request [Demra Ideal College]

### ISSUE THREAD

**Issue by rafidalhaque** [lightoj-dev/bugs-and-features#128]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Demra Ideal College
2. Website: demraidealcollege.edu.bd
3. Logo Url: ![images.jpeg](https://user-images.githubusercontent.com/68812773/153751239-ade9e495-67e2-4a90-9166-3c30c8c8acd9.jpeg)
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/demraidealcollege-bd
