### ISSUE TITLE
Institution add Request [University of Engineering and Technology, Lahore]

### ISSUE THREAD

**Issue by nabeelraza-7** [lightoj-dev/bugs-and-features#129]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: University of Engineering and Technology, Lahore
2. Website: https://uet.edu.pk/
3. Logo Url: https://uet.edu.pk/newsannouncement/newssection/images/2021/december/uetnewlogo.png
4. Country: Pakistan

**Comment by jan876** [comment]
https://lightoj.com/institutions/uet-pk
