### ISSUE TITLE
Suggesting password field in dropdown institute

### ISSUE THREAD

**Issue by mhhabib** [lightoj-dev/bugs-and-features#13]
While selecting an institution name, the dropdown box is showing the auto password field. 

![Untitled](https://user-images.githubusercontent.com/17263976/103503293-fdbf8e00-4e7d-11eb-967a-63671707cae0.png)

**Comment by faiyaz26** [comment]
Are you still facing this issue? What is the browser and os ?

**Comment by mhhabib** [comment]
Yes still showing the same issue with windows chrome

**Comment by faiyaz26** [comment]
Fixed. Will deployed soon
