### ISSUE TITLE
All Questions Are Stuck at Verdict Pending

### ISSUE THREAD

**Issue by TheK098** [lightoj-dev/bugs-and-features#130]
**Describe the bug**
My submissions and many others are being stuck at verdict pending when we submit solutions. It's been over 8 hours and it still hasn't been judged.

**To Reproduce**
1. Go to any problem 
2. Submit a solution
3. Click on Submissions
4. The verdict is stuck on pending

**Expected behavior**
Obviously, it is expected that the solution is judged.

**Screenshots**
<img width="696" alt="Screen Shot 2022-02-16 at 12 38 16 PM" src="https://user-images.githubusercontent.com/63420574/154352977-ec95a62d-1399-4cac-bf4b-2705ecf011ff.png">

**Browser information (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version Apple M1 Macbook Pro - macOS Monterey 12.0.1

**Additional context**
Other people are also facing this issue, so it would be great if it was solved as soon as possible!

**Comment by faiyaz26** [comment]
Thanks for notifying us, we have resolved the issue, All the queued submissions should be judged within 2 hours.
