### ISSUE TITLE
Institution add Request [Jaypee University of Engineering and Technology]

### ISSUE THREAD

**Issue by doomsday861** [lightoj-dev/bugs-and-features#131]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Jaypee University of Engineering and Technology
2. Website: juet.ac.in
3. Logo Url:https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/v1506722151/btif4dxg8rgtfprtffrn.png
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/juet-in
