### ISSUE TITLE
Institution add Request [BGC Trust University Bangladesh]

### ISSUE THREAD

**Issue by WhisperFromAshes** [lightoj-dev/bugs-and-features#132]
1. Institution Name: BGC Trust University Bangladesh
2. Website: www.bgctub.ac.bd
3. Logo Url: https://www.bgctub.ac.bd/templates/common/image/imagesfront/logo.png
4. Country: Bangladesh
**Note: In LightOJ, our uviversity name is mentioned as Begum Gulchemonara Trust University. But it is wrong. It is not official name. You can see the proof from the website of UGC: http://www.ugc-universities.gov.bd/university-detail/54**

**Comment by jan876** [comment]
Fixed. https://lightoj.com/institutions/bgc-trust-bd
