### ISSUE TITLE
LOJ-1074 Data Set Problem.

### ISSUE THREAD

**Issue by partho-das** [lightoj-dev/bugs-and-features#133]
Hi, I think there is a problem with the https://lightoj.com/problem/extended-traffic problem data set. This problem is given for detecting negative cycle. 
But I used just a simple dfs solution to detect negative cycle which, cannot detect every negative cycle it just detected cycle by input order. That can cause the wrong answer. But the judge's data set was not enough strong to catch it.
See this is an example  sample : 
1
10
1 2 3 4 5 6 5 6 5 4

11
1 2 

2 5
2 3

3 4
4 5
5 6 
6 7
7 8
8 9
9 10
10 1

1
5

the output should be
Case 1:
?

But if give it to my code [Extended Traffic](https://paste.ubuntu.com/p/zwcvnTnMzT/) it is giving 
Case 1:
4

See for the sample test case the problem is : 
![loj3](https://user-images.githubusercontent.com/48844163/161467415-85c50fd7-87d9-47d9-bcad-3ef362a99310.png)
![Traverse 2](https://user-images.githubusercontent.com/48844163/161430033-f02f9900-7c3d-4355-a794-96fd0804e51f.png)

if the sample gives 2 5 edge before 2 3 then my code traverses the blue cycle first for that reason my code could not detect the green negative cycle. 

But if the sample gives 2 3 before 2 5 then it can detect the green cycle.

**Comment by jan876** [comment]
Updated the datasets as you suggested. Thanks a lot for the test cases!
