### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by jtorresc1980** [lightoj-dev/bugs-and-features#134]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Universidad De Piura
2. Website: https://www.udep.edu.pe/
3. Logo Url: https://www.udep.edu.pe/wp-content/uploads/2020/08/logo_UDEP.png
4. Country: Perú

**Comment by jan876** [comment]
https://lightoj.com/institutions/udep-pe
