### ISSUE TITLE
Ranklist no longer updates after removing a user form contest

### ISSUE THREAD

**Issue by ChuangSheep** [lightoj-dev/bugs-and-features#137]
**Describe the bug**
The ranking list and submissions history no longer update after removing a user from the contest. 
Error from the api when refreshing the ranklist:
`{"message":"Cannot read property 'problemStat' of undefined","name":"TypeError","status":500}`

**To Reproduce**
1. Create a new Contest, invite at least two users
2. One user should first complete a problem
3. Remove the user
4. The Ranklist will no longer be updated and submissions can no longer be seen by the owner. "Force regenerate Ranklist" does not work and in console the 500 error raises. 

**Expected behavior**
The ranking list and submissions history should still be functional. 

**Screenshots**
<img width="946" alt="image" src="https://user-images.githubusercontent.com/44814054/177214016-ea43271e-72d5-4737-9c29-dcd35cdb1d11.png">
![image](https://user-images.githubusercontent.com/44814054/177216000-48eaa353-d0e4-4915-b12a-d2f3766b73d6.png)

**Browser information (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 103

**Additional context**

**Comment by faiyaz26** [comment]
Hello, we found the bug on the standings/rankings side, fix is on the way. But couldn't reproduce the submissions issue, have you tried refreshing the page?

**Comment by ChuangSheep** [comment]
Hi, thanks for the quick fix. The standings seem to work now.

The problem about submissions: I tried force refresh the site and it will work. However, if I only navigate to the submission and click the filter or refresh button, It won't work and at right bottom side there says `NaN`. 

<img width="472" alt="image" src="https://user-images.githubusercontent.com/44814054/177276325-5e59dcc8-53a8-480f-b1c1-94230bad7759.png">

**Comment by faiyaz26** [comment]
Hello, I am not sure why its happening. I can see on your contest, there are two user on admin section, both are seeing same issue?

**Comment by ChuangSheep** [comment]
Sadly... I just added another user into the contest, and the ranklist fails again. 

<img width="956" alt="image" src="https://user-images.githubusercontent.com/44814054/177526884-f207c773-af0d-4591-bd71-978d17d5ec1b.png">

About the submission - I will check it with the other admin.

**Comment by jan876** [comment]
I found the bug and have put a fix. Let us know if you are still seeing this.

**Comment by ChuangSheep** [comment]
Looks alright now. Thank you for the help.
