### ISSUE TITLE
Bangabandhu Sheikh Mujibur Rahman Digital University, Bangladesh

### ISSUE THREAD

**Issue by Rony7s** [lightoj-dev/bugs-and-features#138]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Bangabandhu Sheikh Mujibur Rahman Digital University, Bangladesh
2. Website: https://bdu.ac.bd
3. Logo Url: https://bdu.ac.bd/assets/images/logo/logo1.png
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/bdu-bd
