### ISSUE TITLE
Compile & Test is treated as a submission. 

### ISSUE THREAD

**Issue by ashikurrahmanaust** [lightoj-dev/bugs-and-features#14]
Compile & Test is Treated as a submission before submitting. 
Only if the solution is submitted then it should be counted as a submission. 
![image](https://user-images.githubusercontent.com/58513095/103504928-11212800-4e83-11eb-9f17-ceaac4313893.png)
![image](https://user-images.githubusercontent.com/58513095/103504944-1c745380-4e83-11eb-9737-947de052e546.png)
Also only sample passed solution is showing verdict Accepted.

**Comment by faiyaz26** [comment]
No, it should not count. If you check your history of last submissions, does it show you the compile and test submissions?

**Comment by ashikurrahmanaust** [comment]
Yes sir,  Submission history include the compile and test submission too.

**Comment by faiyaz26** [comment]
Should be fixed now, reopen if not fixed for you.
