### ISSUE TITLE
Institution add Request [Pabna University of Science and Technology]

### ISSUE THREAD

**Issue by Deadly-Smile** [lightoj-dev/bugs-and-features#140]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Pabna University of Science and Technology
2. Website: https://www.pust.ac.bd/
3. Logo Url: https://www.pust.ac.bd/includes/images/pust_logo.png?key=07
4. Country: Bangladesh

**Comment by faiyaz26** [comment]
Its already created: https://lightoj.com/institutions/pust-bd

**Comment by Deadly-Smile** [comment]
There is **Pabna Science and Technology University** in the search bar, but it is a mistake it should be **Pabna University of Science and Technology**.
