### ISSUE TITLE
Institution add Request "Sheikh Fazilatunnesa Mujib University"

### ISSUE THREAD

**Issue by faysalalmahmud** [lightoj-dev/bugs-and-features#143]
1. Institution Name: **Sheikh Fazilatunnesa Mujib University**
2. Website: https://www.sfmu.edu.bd/
3. Logo Url: https://drive.google.com/file/d/1wEjDi5bx55Pru2hNVtxrzhutYqFyWMJp/view?usp=sharing
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/sfmu-bd
