### ISSUE TITLE
Institution add Request [Tejgaon College]

### ISSUE THREAD

**Issue by mahimerror** [lightoj-dev/bugs-and-features#144]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Tejgaon College
2. Website: https://www.tejgaoncollege.edu.bd/
3. Logo Url: https://www.tejgaoncollege.edu.bd/wp-content/uploads/2022/01/Logo2-1-160x164.png
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/tejgaoncollege-bd
