### ISSUE TITLE
Institution add Request [North China Electric Power University]

### ISSUE THREAD

**Issue by sheam-tech** [lightoj-dev/bugs-and-features#146]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: North China Electric Power University
2. Website: https://www.ncepu.edu.cn/
3. Logo Url: https://upload.wikimedia.org/wikipedia/en/5/5d/North_China_Electric_Power_University_logo.png
4. Country: China

**Comment by jan876** [comment]
https://lightoj.com/institutions/ncepu-cn
