### ISSUE TITLE
Institution add Request [ITS Engineering College]

### ISSUE THREAD

**Issue by daxoron** [lightoj-dev/bugs-and-features#149]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: ITS Engineering College
2. Website: https://www.itsengg.edu.in/
3. Logo Url: https://www.itsengg.edu.in/images/its%20engineering%20college%20logo.png
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/itsengg-in
