### ISSUE TITLE
Getting TLE on previously accepted solutions.

### ISSUE THREAD

**Issue by riadath** [lightoj-dev/bugs-and-features#15]
Username : riadath

I'm getting TLE on the following problems which were Accepted in the previous site.

Problem 1009; Submission ID : 1942790
Problem 1024; Submission ID : 1942452
Problem 1085; Submission ID : 1942786
Problem 1207; Submission ID : 1942886

**Comment by jan876** [comment]
1009, increased time limit and rejudging.

Checking others...

**Comment by jan876** [comment]
1085, increased time limit and rejudging.

**Comment by jan876** [comment]
1207, increased time limit and rejudging.

**Comment by jan876** [comment]
1024, increased time limit and rejudging.

Please close the ticket once all of them pass.
