### ISSUE TITLE
Text color in Rank list not visible

### ISSUE THREAD

**Issue by yousefbinali** [lightoj-dev/bugs-and-features#150]
**Describe the bug**
Text is not visible in rank list in light mode.

**To Reproduce**
1. Go to rank list in a contest
2. 
**Expected behavior**
A visible text

**Screenshots**

**Browser information (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 106.0.5249.119

**Comment by faiyaz26** [comment]
Can you upload a screenshot?

**Comment by yousefbinali** [comment]
![image](https://user-images.githubusercontent.com/75175135/197308991-ff1860f7-e4ed-438e-a993-699c64af2dda.png)
Note: I'm the owner of the contest.

**Comment by jan876** [comment]
Fixed.
