### ISSUE TITLE
 The International University of Scholars

### ISSUE THREAD

**Issue by anikpodder** [lightoj-dev/bugs-and-features#155]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: The International University of Scholars
2. Website: https://ius.edu.bd/
3. Logo Url: https://ius.edu.bd/public/upload/systemSettings/699753.png
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/ius-bd
