### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by mmaazzeenn0-o** [lightoj-dev/bugs-and-features#156]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: October university for modern science and arts
2. Website: https://msa.edu.eg/msauniversity/
3. Logo Url: https://msa.edu.eg/msauniversity/images/MSAUniversity-Official-Logo.png
4. Country: Egypt

**Comment by jan876** [comment]
https://lightoj.com/institutions/mesa-eg
