### ISSUE TITLE
Institution add Request [Netaji Subhas University Of Technology]

### ISSUE THREAD

**Issue by syedaliaatif** [lightoj-dev/bugs-and-features#158]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Netaji Subhas University Of Technology 
2. Website: www.nsut.ac.in
3. Logo Url: http://www.nsit.ac.in/static/images/nsut_logo.png
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/nsut-in
