### ISSUE TITLE
Display local time

### ISSUE THREAD

**Issue by zobayer1** [lightoj-dev/bugs-and-features#160]
**Is your feature request related to a problem? Please describe.**
LightOJ shows UTC time on various interfaces. For example, on the clarification page in the contest author dashboard. And there are other places where timestamps are shown in 12 hours format and 24 hours format. This is a bit jarring and unusual.

**Describe the solution you'd like**
I think it will be more comfortable for users if the same time format was used system-wide, preferably local TZ time.

**Describe alternatives you've considered**
In the personal settings page, time format and timezone could be taken as input from the user.

**Additional context**
Notice timestamp format discrepancies on the following two pages:
1. https://lightoj.com/author/contest/2208/clarifications
2. https://lightoj.com/author/contest/2208/submissions
![clarification](https://user-images.githubusercontent.com/26373865/201978823-fa950a2a-759d-44af-ba60-a0895a12ed18.png)
![submission](https://user-images.githubusercontent.com/26373865/201978835-9713c2fa-7c1e-455b-8391-d076bb60330c.png)

**Comment by jan876** [comment]
Thanks for raising the issue. Fixed.
