### ISSUE TITLE
javascript (nodejs) input format

### ISSUE THREAD

**Issue by samiulalimseam** [lightoj-dev/bugs-and-features#161]
What is the standard input format of javascript accepted by lightOJ?

**Comment by jan876** [comment]
One example: go to https://lightoj.com/problem/greetings-from-lightoj

Click javascript as your language, it will give you an example.

There is a tutorial section for this problem, too with javascript examples.

We use nodejs,

```
var readline = require('readline');

var rl = readline.createInterface(process.stdin, process.stdout);
var caseno = 1;

rl.on('line', function(line) {
    var input = line.split(' ');
    if (input.length == 2) {
        var res = parseInt(input[0]) + parseInt(input[1]);
        console.log(["Case ", caseno, ": ", res].join(""));
        ++caseno;
    }
});

```
