### ISSUE TITLE
Institution add Request [Universidad de las Ciencias Informáticas]

### ISSUE THREAD

**Issue by addielmoldes** [lightoj-dev/bugs-and-features#162]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Universidad de las Ciencias Informáticas
2. Website: https://www.uci.cu/
3. Logo Url: https://scontent-bog1-1.xx.fbcdn.net/v/t39.30808-6/300177564_5725555077477940_8820532459977657231_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=dDqYCsGyoqsAX_3UikP&_nc_ht=scontent-bog1-1.xx&oh=00_AfCna0QEUlVk9qmjZj-87UWKSi8vjKe4FDHMWYwYbJc1gg&oe=637EFA97
4. Country: Cuba

**Comment by jan876** [comment]
https://lightoj.com/institutions/uci-cu
