### ISSUE TITLE
Infinite loading animation in problem category cards

### ISSUE THREAD

**Issue by tasfik007** [lightoj-dev/bugs-and-features#163]
While navigating to lightoj problem category page loading bars in each card are loading for infinite time.

1. Go to [lightoj problem category](https://lightoj.com/problems/category)
2. View the problem category cards
3. Wait for some time
4. Loading will not stop

Loading bars should stop and reflect percentage of problems that a user have solved.

![image](https://user-images.githubusercontent.com/38793982/203964360-8649df1a-0a8e-428e-a5b9-f20966b750c2.png)

 - OS: windows
 - Browser: firefox
 - Version: 107.0

**Comment by jan876** [comment]
Fixed.

**Comment by tasfik007** [comment]
Acknowledged with thanks Bhai. Also would love to contribute in the main project itself, do let me know if it is possible.
