### ISSUE TITLE
Cannot see others' solutions in Leaderboard

### ISSUE THREAD

**Issue by facug91** [lightoj-dev/bugs-and-features#164]
**Describe the bug**
I solved the problem https://lightoj.com/problem/curious-robin-hood, and then I wanted to see some of the solutions from other users, but I get a code 403 error. I think this is a bug, but it might be something you want, to prevent users from seing others' solutions. In that case, I think the links of submissions shouldn't be clickable links.

**To Reproduce**
Log in, go to the problem https://lightoj.com/problem/curious-robin-hood, and try to open any submission from the Leaderboard.

**Expected behavior**
I thought I could see others' solutions.

**Screenshots**
![image](https://user-images.githubusercontent.com/7832961/204964127-a627ec59-a3ac-4a2a-abae-0009ceaf070c.png)

**Browser information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Brave
 - Version: 1.45.133

**Comment by jan876** [comment]
Fixed. For now, you will only be able to see your submission. We are working on a feature to show other submissions as well.
