### ISSUE TITLE
Institution add Request [Fr. Conceicao Rodrigues Institute of Technology]

### ISSUE THREAD

**Issue by theabbie** [lightoj-dev/bugs-and-features#166]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Fr. Conceicao Rodrigues Institute of Technology
2. Website: https://www.fcrit.ac.in
3. Logo Url: https://fcrit.ac.in/img/fcritlogo.png
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/fcrit-in
