### ISSUE TITLE
Submission and count bug

### ISSUE THREAD

**Issue by Agent473886** [lightoj-dev/bugs-and-features#167]
**Describe the bug**
After completing the problems , when I submit it , it doesn't show that I've solve the problem , as an example , I have solved 6 problems , when I solve the 7th one , it doesn't show that I've completed 7 problems
**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser information (please complete the following information):**

**Additional context**

**Comment by faiyaz26** [comment]
It takes time to refresh the stats, but its working. Let me know if it is still not refreshed. Provide your handle/username, last problem you solved to debug further.
