### ISSUE TITLE
Not showing unsolved problem correctly.

### ISSUE THREAD

**Issue by CLown1331** [lightoj-dev/bugs-and-features#168]
**Describe the bug**
Not showing unsolved problem in [warmup](https://lightoj.com/problems/category/warm-up) category.

**To Reproduce**

**Expected behavior**
Unsolved problem should show up.

**Screenshots**
<img width="724" alt="image" src="https://user-images.githubusercontent.com/11315571/210585358-326bd575-4bc2-4041-8cee-75d514cabf60.png">
<img width="951" alt="image" src="https://user-images.githubusercontent.com/11315571/210584690-fffb3abf-2321-44ad-bf43-8eb68e0c16af.png">

**Browser information (please complete the following information):**
 - Windows 11
 - Edge
 - Version 108.0.1462.54 (Official build) (64-bit)

# **Additional context**

**Comment by jan876** [comment]
Fixed.
