### ISSUE TITLE
Contest is not showing up when the contest type is team

### ISSUE THREAD

**Issue by vjharish88** [lightoj-dev/bugs-and-features#169]
**Describe the bug**
When I created the contest for the team with contestant type as team, it is not showing up. When the contest is created for individual, it is working fine. Please correct this bug.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser information (please complete the following information):**

**Additional context**

**Comment by jan876** [comment]
Should be fixed now. Thanks for reporting.
