### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by AlSaimun** [lightoj-dev/bugs-and-features#170]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Feni Computer Institute (FCI)
2. Website: https://fci.gov.bd/
3. Logo Url: https://fci.gov.bd/public/setting/220521_02_10_42.jpg
4. Country: Bangladesh

**Comment by abidhasan11** [comment]
Institution Name: Uttara High School and College
    Website: http://uhscdhaka.edu.bd/
    Logo Url: 
![image](https://user-images.githubusercontent.com/123868184/215319972-fde6568d-5904-423e-a14a-26a2d91e5e64.png)

    Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/fci-bd
https://lightoj.com/institutions/uhscdhaka-bd
