### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by golamrabbi77** [lightoj-dev/bugs-and-features#171]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Bangladesh Army University of Engineering & Technology

2. Website: https://bauet.ac.bd/
3. Logo Url: https://bauet.ac.bd/eee/wp-content/themes/wpt-unipro-ius/assets/images/BAUET-Logo-250x244.png
4. Country: Bangladesh 
![BAUET-Logo-250x244](https://user-images.githubusercontent.com/114388633/216040970-69a5df27-45b0-474f-ae7b-491a6c8685b8.png)

**Comment by jan876** [comment]
https://lightoj.com/institutions/bauet-bd
