### ISSUE TITLE
Dark mode Issues

### ISSUE THREAD

**Issue by ridoystarlord** [lightoj-dev/bugs-and-features#173]
**Describe the bug**
There is an issues in dark mode on settings page. As i love to use dark mode so enable the dark mode in you web settings but when i try to edit my details i got and issues in INSTITUTION and PREFERRED LANGUAGE search component. Also have color issues in country dropdown which i guess must be solved in dark mode. I can help you to solve it.

**To Reproduce**
1. Go to 'settings'
2. Enable dark mode
3. check the institution and language section which is white and select any of them.
![Screenshot_16](https://user-images.githubusercontent.com/77241744/218532914-346e7d77-ddf3-4550-99bb-32a9185308ed.png)

**Expected behavior**
This should be fix in dark mode so that user experience would be good

**Comment by jan876** [comment]
Fixed.
