### ISSUE TITLE
Duplicate teams are created with the same team handle

### ISSUE THREAD

**Issue by jeyincanada** [lightoj-dev/bugs-and-features#176]
1. Duplicate teams are created with the same team handle.
2. Unable to delete a team

We are running the programming contest with around 40 participants during the next week. Can you please give the email id of the administrator of LightOJ platform.
![duplicateTeams](https://user-images.githubusercontent.com/128208254/226087481-c0f5318d-7498-4ff5-a427-be0a88b5d8b8.png)

**Comment by jan876** [comment]
I just verified and it seems that there is only one team with the team-handle, could you please send a bit more details at admins@lightoj.com?

**Comment by jan876** [comment]
One is team-ediboro2, another one is team-edinboro2 (there is an extra **n**)

**Comment by faiyaz26** [comment]
Email of the admins: admins@lightoj.com
