### ISSUE TITLE
Adding a problem - non-sample dataset

### ISSUE THREAD

**Issue by jeyincanada** [lightoj-dev/bugs-and-features#178]
I have created my own problem. Even though I added a non-sample dataset, still I am getting the error highlighted in red. Also, the problem status set to ready is highlighted in red. Please refer the screenshot

![lightOJError](https://user-images.githubusercontent.com/128208254/226152831-cb9ed45f-8b39-45d7-b028-ce27d01e7969.png)

**Comment by jan876** [comment]
You just need to set the files to active.

There are two status:

Ready for testing
Ready

You need to set it to 'ready'.

**Comment by jeyincanada** [comment]
How do you name the other sample test input and output files? Should it non-sample1.in, non-sample2.in and so forth?

**Comment by faiyaz26** [comment]
sample_1.in

large_test_1.in

corner_case.in
