### ISSUE TITLE
What is this ?

### ISSUE THREAD

**Issue by jeyincanada** [lightoj-dev/bugs-and-features#180]
What does these numbers 1(11) etc indicates? Please see the attached screenshot.
![lightOJQuery](https://user-images.githubusercontent.com/128208254/227559851-0bbb16dc-32f0-4b1f-bfbd-972e833eb6a3.png)

**Comment by faiyaz26** [comment]
Number of submission before getting accepted (Time Penalty).

Time penalty calculation happens according to ACM ICPC rule

he time consumed for a solved problem is the time elapsed from the beginning of the contest to the submittal of the first accepted run plus 20 penalty minutes for every previously rejected run for that problem. There is no time consumed for a problem that is not solved

https://icpc.global/regionals/rules#:~:text=The%20time%20consumed%20for%20a,problem%20that%20is%20not%20solved.
