### ISSUE TITLE
Make the interface for problem input clearer

### ISSUE THREAD

**Issue by PEZ** [lightoj-dev/bugs-and-features#181]
**Is your feature request related to a problem? Please describe.**

When solving the first problem in the default language. I think it was done version of C++. Then there's a scaffold handling the input and I just had to implement a function body. But when trying it for Clojure there was no such scaffold and no instructions on how to get the input. 

**Describe the solution you'd like**

I'd want an easily accessible (from the page where I am solving the problem) information about how the input is made available to my program. 

**Describe alternatives you've considered**

An alternative could be a scaffold/template that is there also for other languages than done default ones, that handles the reading of the input to some variables. And then I could take it from there when solving the problem.

* See also: #175

**Additional context**

I was testing the first problem from my phone (an iPhone) so maybe this info actually is there somewhere, but just not obviously enough for me using my phone.

**Comment by jan876** [comment]
added
