### ISSUE TITLE
Institution add Request [Malawi University of Business and Applied Sciences]

### ISSUE THREAD

**Issue by darlingson** [lightoj-dev/bugs-and-features#182]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Malawi University of Business and Applied Sciences 
2. Website: http://mubas.ac.mw
3. Logo Url:
4. Country: Malawi

**Comment by jan876** [comment]
https://lightoj.com/institutions/mubas-mw
