### ISSUE TITLE
Institution add Request [Government Yasin College]

### ISSUE THREAD

**Issue by AkibAzmain** [lightoj-dev/bugs-and-features#183]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name:  Government Yasin College
2. Website:  https://www.govtyasincollege.edu.bd/
3. Logo Url:  https://www.govtyasincollege.edu.bd/wp-content/uploads/2021/03/cropped-cropped-College-Logo-150x150.png
4. Country:  Faridpur, Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/govtyasincollege-bd
