### ISSUE TITLE
Kotlin with Compilation Error

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [lightoj-dev/bugs-and-features#185]
**Describe the bug**

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
/usr/lib/kotlinc/bin/kotlinc: line 80: 33941 Killed                  "${JAVACMD:=java}" $JAVA_OPTS "${java_args[@]}" -cp "${kotlin_app[@]}" "${kotlin_args[@]}"
```

**To Reproduce**
1. Open submission https://lightoj.com/submission/2798853. If this page is not public, then the code is [here](https://pl.kotl.in/dSGcU_A1u)
2. Open [the problem](https://lightoj.com/problem/guilty-prince) and use the code in the previous page
3. Click "Run on Samples": sometime success (Sample Passed), sometime "Compilation Error"
5. Click on "Submit": "Compilation Error"

**Expected behavior**
The code should always be compiled successfully.

**Screenshots**
![image](https://github.com/lightoj-dev/bugs-and-features/assets/24372782/481acc28-651b-4d42-af91-15d76f53dd72)

![image](https://github.com/lightoj-dev/bugs-and-features/assets/24372782/46b15df7-954a-44b8-a0b2-00b29a3eb694)

![image](https://github.com/lightoj-dev/bugs-and-features/assets/24372782/2b357757-c17b-4e0e-8ffa-9303ba84625d)

**Browser information (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser Edge Version 113.0.1774.50 (Official build) (64-bit)

**Comment by xuan-nguyen-swe** [comment]
Oh, if I add `import java.util.*`, it's success.
But the error message is misleading.

**Comment by xuan-nguyen-swe** [comment]
From the same code, that uses `readLine()` to read input.
Now, I want to use `bufferedReader`, I get Compilation Error again. See [code here](https://pl.kotl.in/PX3YZENrL)

![image](https://github.com/lightoj-dev/bugs-and-features/assets/24372782/4508e324-a80f-434a-9cd6-dc7fa3ba9b91)

**Comment by xuan-nguyen-swe** [comment]
Not sure if that's a bug of kotlin compiler or the configuration of LightOJ.

**Comment by xuan-nguyen-swe** [comment]
Well, now try the accepted code again, it fails.
So, basically, unpredictable when the code is accepted or fails with Compilation Error.

**Comment by jan876** [comment]
Thanks for reporting the issue. It was actually a combination of both. Kotlin requires a lot of memory to compile and also the old kotlin was not happy with the java version. We fixed this and rejudged all the submissions.

Keeping the ticket open, please close this if it solved the issue. Thanks.

**Comment by xuan-nguyen-swe** [comment]
> Thanks for reporting the issue. It was actually a combination of both. Kotlin requires a lot of memory to compile and also the old kotlin was not happy with the java version. We fixed this and rejudged all the submissions.
> 
> Keeping the ticket open, please close this if it solved the issue. Thanks.

Wow! Thanks! it works now. Not tested with other problems, but at least, my code passed the mentioned problem immediately on the first try.
