### ISSUE TITLE
Kotlin: Compilation Failed due to taking longer than expected

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [lightoj-dev/bugs-and-features#189]
**Describe the bug**
Cannot compile hello world Kotlin code.

**To Reproduce**
1. Go to any problem, such as https://lightoj.com/problem/dna-prefix
2. Select "Kotlin"
3. Run the code `fun main() { println("Hi") }`

**Expected behavior**
Should compile and successfully print the output and report success or fail.

**Screenshots**
![image](https://github.com/lightoj-dev/bugs-and-features/assets/24372782/2bac1679-8916-48db-b098-3548ebfe9240)

**Browser information (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge Version 114.0.1823.51 (Official build) (64-bit)

**Comment by xuan-nguyen-swe** [comment]
Now it can compile Kotlin again, but not enough memory with a simple Trie solution.
I think the Kotlin environment is very unstable, and the memory assigned to some problems is usually not enough?

**Comment by jan876** [comment]
Increased memory for kotlin and rejudged all the submissions, thanks for reporting.
