### ISSUE TITLE
Quantum Cosmo School & College.

### ISSUE THREAD

**Issue by Majiulhakimquanta** [lightoj-dev/bugs-and-features#190]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Quantum Cosmo School & College.
2. Website: https://quantummethod.org.bd
3. Logo Url: https://files.quantummethod.org.bd/media/image/static_content/quantum_foundation_logo_20210919.png
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/quantummethod-bd
