### ISSUE TITLE
dhubni kanchibari degree college, Sundarganj, Gaibandha.

### ISSUE THREAD

**Issue by ferarilalon** [lightoj-dev/bugs-and-features#191]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: dhubni kanchibari degree college, Sundarganj, Gaibandha.
2. Website: n/a
3. Logo Url: n/a
4. Country: Bangladesh.

**Comment by faiyaz26** [comment]
Without website and logo we can't add your institution.

**Comment by EdisonOspina16** [comment]
Nombre de la institución: Universidad de medelin 
Sitio web: https://udemedellin.edu.co/
URL del logotipo: https://carreras.com.co/wp-content/uploads/2019/06/logo-universidad-de-medellin.jpg
Pais: colombia, medellin

**Comment by jan876** [comment]
https://lightoj.com/institutions/udemedellin-co
