### ISSUE TITLE
Institution add Request: Anderson Serangoon Junior College

### ISSUE THREAD

**Issue by jeromepalayoor** [lightoj-dev/bugs-and-features#192]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Anderson Serangoon Junior College
2. Website: https://www.asrjc.moe.edu.sg/
3. Logo Url: https://www.asrjc.moe.edu.sg/images/Master-Horizontal-Logo-reduced-380x99%20(1).png
4. Country: Singapore

**Comment by jan876** [comment]
https://lightoj.com/institutions/asrjc-sg
