### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by Putin57** [lightoj-dev/bugs-and-features#193]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Institute of Science and Technology
2. Website: https://www.ist.edu.bd
3. Logo Url: ![image](https://github.com/lightoj-dev/bugs-and-features/assets/75845610/7da51ea4-cd6d-4cf3-b5a9-018661241a89)
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/ist-bd
