### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by Putin57** [lightoj-dev/bugs-and-features#194]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Jatir Janak Bangabandhu Sheikh Mujibur Rahman Government College
2. Website: https://www.jjbbsmrgc.edu.bd
3. Logo Url: ![image](https://github.com/lightoj-dev/bugs-and-features/assets/75845610/3aa56099-d026-4786-922e-78c8fbaac524)
4. Country:Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/jjbbsmrgc-bd
