### ISSUE TITLE
THE ENTIRE SITE IS DOWN, ALL MY NEW CONTESTANTS TRYING TO REGISTER ARE REACHING OUT

### ISSUE THREAD

**Issue by dylan1006498** [lightoj-dev/bugs-and-features#196]
**Describe the bug**
503 Bad Gateway error on anything in the lightoj.com domain

**To Reproduce**

**Expected behavior**
Go onto the website
**Screenshots**

**Browser information (please complete the following information):**
Mac
Safari and Chrome
Idk
**Additional context**

**Comment by faiyaz26** [comment]
We are facing a major outage in our judging server, currently there is no
ETA to fix the issue.
