### ISSUE TITLE
Feni Central High School

### ISSUE THREAD

**Issue by rayhan300** [lightoj-dev/bugs-and-features#199]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name :Feni Central High School
2. Website: https://www.fenicentralhighschool.com/
3. Logo Url: https://www.fenicentralhighschool.com/images/logo.jpg
4. Country:Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/fenicentralhighschool-bd
