### ISSUE TITLE
Can not save profile changes

### ISSUE THREAD

**Issue by pallab-gain** [lightoj-dev/bugs-and-features#2]
What I did
 - Go to the Settings page
-  Changed country to Finland
-  Press `Save Changes`

What to expect
 - Should successfully save my changes

I am getting an error  ( Maximum 20 characters are allowed ).  More details in the attachment 

![Account-settings-LightOJ (1)](https://user-images.githubusercontent.com/1187721/97091142-508cf600-1642-11eb-9f2b-23bd45b78e9f.png)

**Comment by faiyaz26** [comment]
Hello, 
Sorry for this experience, it was actually error message for email. Anyway, updated it. You should be able to set the country now. Let me know if you still see this problem.
