### ISSUE TITLE
Institution add Request [Dhaka College, Dhaka]

### ISSUE THREAD

**Issue by solaimantanvir** [lightoj-dev/bugs-and-features#201]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: **Dhaka College, Dhaka**
2. Website: https://dhakacollege.edu.bd/
3. Logo Url: https://dhakacollege.edu.bd/frontend/img/logo.png
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/dhakacollege-bd
