### ISSUE TITLE
Institution add Request [Singapore Polytechnic]

### ISSUE THREAD

**Issue by Zafyree3** [lightoj-dev/bugs-and-features#202]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Singapore Polytechnic
2. Website: https://www.sp.edu.sg/
3. Logo Url: https://www.sp.edu.sg/images/default-source/default-album/sp-logo.png?sfvrsn=e2b890e2_4
4. Country: Singapore

**Comment by jan876** [comment]
https://lightoj.com/institutions/sp-sg
