### ISSUE TITLE
Institution add Request [R. P. Shaha University]

### ISSUE THREAD

**Issue by ankanroy96** [lightoj-dev/bugs-and-features#203]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: R. P. Shaha University
2. Website: https://rpsu.ac.bd/
3. Logo Url: https://rpsu.ac.bd/
4. Country: Bangladesh

**Comment by jan876** [comment]
I think it already exists: https://lightoj.com/institutions/rpsu-bd
