### ISSUE TITLE
automatic authentication failed

### ISSUE THREAD

**Issue by evanmozumder** [lightoj-dev/bugs-and-features#205]
**Describe the bug**
My account is logged in my pc. But after i reset password from my phone it still logged in my pc without showing any validation error. But it works fine re-logging.

**To Reproduce**
1. Log in account in device-1 and device-2
2. reset password from device-2
3. nothing happen with device-1 until you logged out from device-1

**Expected behavior**
after resetting password it should logout from all other devices and force to re-login

**Browser information (please complete the following information):**
 - OS: windows
 - Browser Brave
 - Version 1.60.118

**Comment by faiyaz26** [comment]
Hello, thanks for submitting the information.

LightOJ is not considered as some website which requires this kind of security implementation. So closing the issue
