### ISSUE TITLE
Institution add Request [Bogura Cantonment Public School and College]

### ISSUE THREAD

**Issue by mehedihasrifat** [lightoj-dev/bugs-and-features#206]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Bogura Cantonment Public School and College
2. Website: https://www.bcpsc.edu.bd/
3. Logo Url: https://vortibd.com/media/icon/2023_10_23_04_59_09_bcpsc.png
4. Country: Bangladesh

**Comment by mehedihasrifat** [comment]
Sir, did you add my institution?

Regards.

**Comment by jan876** [comment]
https://lightoj.com/institutions/bcpsc-bd

**Comment by mehedihasrifat** [comment]
Sir, I really appreciate that! Assalamu Alaikum, Sir!
