### ISSUE TITLE
Institution add Request [Chattogram Collegiate School, Chattogram, Bangladesh]

### ISSUE THREAD

**Issue by Rawnak-Shuvro** [lightoj-dev/bugs-and-features#208]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Chattogram Collegiate School, Chattogram
2. Website: http://www.ctgcs.edu.bd/
3. Logo Url: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.facebook.com%2Fctgcollegiate%2F&psig=AOvVaw2OzImDb0naOv21SD8pZyAs&ust=1702476724682000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCOjIj5CKioMDFQAAAAAdAAAAABAD
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/ctgcs-bd
