### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by Luckyaman** [lightoj-dev/bugs-and-features#210]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: The Millennium University
2. Website:http://www.themillenniumuniversity.edu.bd/
3. Logo Url:https://media.licdn.com/dms/image/D560BAQGIz97CcBOkIg/company-logo_200_200/0/1685721542048?e=1714003200&v=beta&t=fPpwzse0MKyTlkIVsg8Urix5pevXlo9mJd6WQnije04
4. Country:Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/tmu-bd
