### ISSUE TITLE
Institution add Request [Issyk-Kul State University after Kasym Tynystanov]

### ISSUE THREAD

**Issue by zhanybekovich** [lightoj-dev/bugs-and-features#211]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Issyk-Kul State University after Kasym Tynystanov
2. Website: http://main.iksu.kg/
3. Logo Url: http://main.iksu.kg/wp-content/uploads/2020/01/cropped-logo.png
4. Country: Kyrgyz Republic

**Comment by jan876** [comment]
https://lightoj.com/institutions/iksu-kg
