### ISSUE TITLE
Institution add Request [Sheikh Hasina University]

### ISSUE THREAD

**Issue by thewoahguy24** [lightoj-dev/bugs-and-features#212]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Sheikh Hasina University
2. Website: https://www.shu.edu.bd
3. Logo Url: https://www.shu.edu.bd/wp-content/uploads/2021/03/SHU-logo-small.jpg
4. Country: Bangladesh
![SHU-logo  WBG](https://github.com/lightoj-dev/bugs-and-features/assets/127776740/217324c6-eef0-4faa-9857-056a6fa89bc7)

**Comment by jan876** [comment]
https://lightoj.com/institutions/shu-bd
