### ISSUE TITLE
Institution add Request [Ho Chi Minh University of Information Technology]

### ISSUE THREAD

**Issue by kirazero17** [lightoj-dev/bugs-and-features#213]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Ho Chi Minh University of Information Technology
2. Website: https://uit.edu.vn/
3. Logo Url: https://upload.wikimedia.org/wikipedia/commons/0/00/Logo_UIT_updated.svg
4. Country: Vietnam

**Comment by jan876** [comment]
https://lightoj.com/institutions/uit-vn
