### ISSUE TITLE
Institution add Request [College of Engineering Guindy]

### ISSUE THREAD

**Issue by cegprakash** [lightoj-dev/bugs-and-features#217]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: College of Engineering Guindy
2. Website: https://ceg.annauniv.edu/
3. Logo Url: https://ceg.annauniv.edu/assets/images/CEG_col.png
4. Country: India

**Comment by jan876** [comment]
https://lightoj.com/institutions/ceg-in
