### ISSUE TITLE
Institution Add Request

### ISSUE THREAD

**Issue by partho-das** [lightoj-dev/bugs-and-features#22]
Institution Name : Dhaka City College
Institution website : [https://www.dhakacitycollege.edu.bd/](https://www.dhakacitycollege.edu.bd/)
Institution logo : [Dhaka City College](https://media-exp1.licdn.com/dms/image/C4E0BAQHulF44wLuE_A/company-logo_200_200/0/1519900969523?e=2159024400&v=beta&t=FGInYAfoh7XZ7ei8iwB2MxBbyyTgaYXobg0LVbi5ty4)
Country : Bangladesh

**Comment by jan876** [comment]
Added.

**Comment by partho-das** [comment]
That's Great. Thanks, to the LOJ team.
