### ISSUE TITLE
Google REcaptcha not showing

### ISSUE THREAD

**Issue by Blinkrider** [lightoj-dev/bugs-and-features#23]
I tried to reset the password but failed and didn't find any Recaptcha

**Comment by faiyaz26** [comment]
Can you give a screenshot? Have you tried refreshing the page?

**Comment by Blinkrider** [comment]
Ya, I did, and The ReCaptcha won't show up, and I can't log(reset the password) in without it.
**Screenshot** 
![Capture](https://user-images.githubusercontent.com/47927896/103589166-057e4180-4f15-11eb-80e9-c7cb56c5370f.PNG)

**Comment by faiyaz26** [comment]
Sorry for the inconvenience. It should be fixed now, please refresh the page. Reopen the issue if you still see the error
