### ISSUE TITLE
Institution add request

### ISSUE THREAD

**Issue by azadatiqur** [lightoj-dev/bugs-and-features#29]
Institution Name : Notre Dame College
Logo: https://upload.wikimedia.org/wikipedia/en/thumb/8/84/Logo_of_Notre_Dame_College%2C_Dhaka.svg/1200px-Logo_of_Notre_Dame_College%2C_Dhaka.svg.png
Website: https://ndc.edu.bd/
Country: Bangladesh

**Comment by jan876** [comment]
Done.
