### ISSUE TITLE
The User avatar doesn't fit

### ISSUE THREAD

**Issue by rksazid** [lightoj-dev/bugs-and-features#30]
**Describe the bug**
The User avatar image doesn't fit

**To Reproduce**
1. Go to '[https://lightoj.com/settings](https://lightoj.com/settings)'
2. Upload a random size image (Mostly happens on a Landscape image)
3. The image doesn't fit both navbar (top-right) & User block (top-left)

**Expected behavior**
The user avatar should be fit on the image container whatever size it has.

**Screenshots**
Current:
![Screenshot from 2021-01-05 20-42-53](https://user-images.githubusercontent.com/22630919/103659515-af51e280-4f96-11eb-9455-b1183a6a8efa.png)

![Screenshot from 2021-01-05 20-43-05](https://user-images.githubusercontent.com/22630919/103659672-e0caae00-4f96-11eb-9705-f5b3aca94e2c.png)

Expected:
![Screenshot from 2021-01-05 20-49-02](https://user-images.githubusercontent.com/22630919/103660187-84b45980-4f97-11eb-92b1-ea3a5d73a570.png)

![Screenshot from 2021-01-05 20-49-09](https://user-images.githubusercontent.com/22630919/103660202-8847e080-4f97-11eb-98a3-27ab2bfd4ed1.png)

**Browser information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser: Chrome

**Probable Solution**
Add: object-fit: cover;
as CSS attribute in those image.

Example:
1. In the navbar
```
.navbar .navbar-item.is-account img {
    object-fit: cover;
}
```

2. In the sidebar
```
.settings-sidebar .settings-sidebar-inner .user-block .avatar-wrap img {
    object-fit: cover;
}
```

**Comment by faiyaz26** [comment]
Hello, thanks a lot for the bug report and also giving the solution as well. I have added it, will be released on next cycle. Closing the issue now.
