### ISSUE TITLE
Responsive issue on submission card

### ISSUE THREAD

**Issue by raydwaipayan** [lightoj-dev/bugs-and-features#33]
**Describe the bug**
Card on problem submission is not responsive.

**To Reproduce**
1. Submit a problem
2. Reduce the width of viewport by half, part of the card gets hidden

**Expected behavior**
The card should resize itself.

**Browser information (please complete the following information):**
 - OS: Manjaro Linux (XFCE)
 - Chrome

**Comment by faiyaz26** [comment]
Please provide a screenshot

**Comment by faiyaz26** [comment]
closing it due to inactivity.
