### ISSUE TITLE
Can't create new Task

### ISSUE THREAD

**Issue by NaimulIslam9m** [lightoj-dev/bugs-and-features#35]
I'm logged in but can't create a task.

Is this a but or there are some rules that I'm not following?

<a><img src="https://i.ibb.co/HDMnyfB/image.png"></a>

**Comment by faiyaz26** [comment]
Hello.

How you got access to that page to create new task? It was not supposed to be accessible, we are still working on it.

**Comment by faiyaz26** [comment]
Ah sorry, we are supposed to hide it from the navbar. We will make it public, when we are finished with contest feature.
