### ISSUE TITLE
Edge Browser issue

### ISSUE THREAD

**Issue by ftowaha** [lightoj-dev/bugs-and-features#36]
### **Take from edge**
![Problems-LightOJ (1)](https://user-images.githubusercontent.com/64473571/103913389-ab5ac780-5132-11eb-8973-024da88f83d4.png)
### **Take from chrome**
![Problems-LightOJ](https://user-images.githubusercontent.com/64473571/103913395-ae55b800-5132-11eb-9c0b-b2c58c404054.png)
### **Take from edge**
![Home-LightOJ (1)](https://user-images.githubusercontent.com/64473571/103913398-aeee4e80-5132-11eb-98f8-136c00ae573e.png)
### **Take from chrome**
![Home-LightOJ](https://user-images.githubusercontent.com/64473571/103913400-af86e500-5132-11eb-82c6-c2e2f37980a8.png)

**Comment by ftowaha** [comment]
### **Can't read problem.**
![How-Cow-LightOJ](https://user-images.githubusercontent.com/64473571/103915319-42288380-5135-11eb-9ee2-1a8fa463413f.png)

**Comment by faiyaz26** [comment]
Hello, I am using edge on mac. Its working fine for me. Actually during the whole development I have tested with Edge. Is it the latest version of edge browser? What is your OS? And if possible, could you look into the browser console, do you see any error there?

**Comment by ftowaha** [comment]
Thank you brother. Problem solved.
