### ISSUE TITLE
Responsive issue for recaptcha on mobile view

### ISSUE THREAD

**Issue by abu-rifat** [lightoj-dev/bugs-and-features#37]
**Problem Description**
On the mobile login view the recaptcha have some responsive or css issue.

**To Reproduce**
1. Go to login on mobile view.
2. See error.

**Expected behavior**
The recaptcha should be center aligned.

**Screenshots**
![Screenshot_20210107_230408](https://user-images.githubusercontent.com/26666369/103922261-b49d6180-513d-11eb-8a6f-c0f49b4fc17e.jpg)

**Browser information (please complete the following information):**
 - OS: [Android]
 - Browser [chrome]
 - Version [86.0.4240.110]

**Comment by faiyaz26** [comment]
it will be fixed on next release.
