### ISSUE TITLE
Donut chart has same color for compilation error, accepted ones and wrong answer. 

### ISSUE THREAD

**Issue by warhammer327** [lightoj-dev/bugs-and-features#38]
**Description**
The Donut chart that is supposed to show stats, has same color for compilation error, wrong answers and the solves those are accepted. It gets very confusing to understand what's what without hovering mouse over it. 

**To Reproduce**
1. Go to 'https://lightoj.com/'
2. Login 
3. Take a look at the Donut chart on the right side of the screen.
4. It does not identify different outputs such as accepted, wrong answer, compilation error with different color. 

**Expected behavior**
The chart should show different colors for different outputs. 

**Screenshots**
The chart on the right side, below the solve and submission count. 
![Screenshot from 2021-01-08 02-22-56](https://user-images.githubusercontent.com/34890748/103941148-a446b000-5158-11eb-8305-4afae22e930f.png)

**Browser information (please complete the following information):**
 - OS: Linux (PopOs)
 - Browser: Brave
 - Version: 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)

**Comment by faiyaz26** [comment]
Its updated, please check now.
