### ISSUE TITLE
Sort by "User solved"

### ISSUE THREAD

**Issue by Mehedi-Hassan** [lightoj-dev/bugs-and-features#43]
When learning a new topic, many of us solved problems by checking the number of users solved them (like codeforces). But now I have to open a problem, go to statistics and check solve count, keep in mind number of solves, sort manually and finally select one. Though there is an option to sort by solved/attempted, a problem solved by **130** out of 140 attempted is definitely harder than a problem solved by **2000** out of 3000 attempted.

**Comment by faiyaz26** [comment]
We will add this number in future, but for now, you can use sorting by difficulty, which is essentially same.

**Comment by jan876** [comment]
Done.
