### ISSUE TITLE
FR: Toggle Editor

### ISSUE THREAD

**Issue by rebornplusplus** [lightoj-dev/bugs-and-features#45]
![image](https://user-images.githubusercontent.com/18555205/104257009-9ec5ce80-54a6-11eb-9dbe-cde9c9c12d58.png)

Requesting "Toggle options" for the editor on the right, so that it'll collapse to the right if wanted. Currently I can push the editor to be small, in terms of width, but can't push the vertical border all the way.

**Comment by faiyaz26** [comment]
Now you can. :) Refresh the page, click on the collapse button
