### ISSUE TITLE
Crack Picture in dark mode

### ISSUE THREAD

**Issue by Munmud** [lightoj-dev/bugs-and-features#46]
While solving this [LOJ-1353](https://lightoj.com/problem/paths-in-a-tree) in dark mode, I found the picture cracked. See the picture below.

![fdd](https://user-images.githubusercontent.com/53787290/104269498-a3977c00-54c0-11eb-9231-415ea0effe46.PNG)

**Comment by faiyaz26** [comment]
Fixed.
