### ISSUE TITLE
Email verification Error

### ISSUE THREAD

**Issue by gh0stst0ries** [lightoj-dev/bugs-and-features#47]
**Describe the bug**
There was an error in verifying email address. An email verification link was sent to my email address., but it is not working. And there is no option to send the verification email again. 

**Screenshots**
![Screenshot (21)](https://user-images.githubusercontent.com/77400246/104475048-d8065780-55e8-11eb-9ec8-c6578406b137.png)

**Comment by faiyaz26** [comment]
Could you share the verification link here?

**Comment by faiyaz26** [comment]
Or forward the email to faiyaz26@gmail.com

**Comment by gh0stst0ries** [comment]
> 
> 
> Or forward the email to [faiyaz26@gmail.com](mailto:faiyaz26@gmail.com)

I have forwarded the email. Please check your email.
