### ISSUE TITLE
Possibly insufficient system tests in the problem: hit-the-light-switches

### ISSUE THREAD

**Issue by RobinHood3082** [lightoj-dev/bugs-and-features#48]
**A custom test fails some AC codes, and passes some. The custom test seems to be correct according to problem description.**

**Custom Input**
1
7 7
1 2
2 3
3 4
4 1
5 6
6 7
7 5

**Expected Output**
Case 1: 2

**Expected Output of Faulty Submission**
Case 1: 1

**Faulty Submission Link**
https://lightoj.com/submission/1952307 (AC)
if not visible, try: https://ideone.com/AfQPiL (same as above)

**Compiler Information**
 - C++17 (g++ 7.5.0)

**Comment by jan876** [comment]
Updated the dataset. Thanks for reporting. Also changed some params.
