### ISSUE TITLE
Override allignment in submission

### ISSUE THREAD

**Issue by Munmud** [lightoj-dev/bugs-and-features#49]
[Check Here](https://lightoj.com/submissions?problemId=1116)
![allign](https://user-images.githubusercontent.com/53787290/104731543-0a898f00-5766-11eb-8a60-6ce41082b393.PNG)

https://user-images.githubusercontent.com/53787290/104731558-11b09d00-5766-11eb-982c-9c138284b11e.mp4

**Comment by faiyaz26** [comment]
Its a feature not bug. https://buefy.org/documentation/field#label-position
