### ISSUE TITLE
Not be able to change email address 

### ISSUE THREAD

**Issue by Kimbbakar** [lightoj-dev/bugs-and-features#50]
**Describe the bug**
Trying to update the old email address but it is not being updated even though it showing a success message.  

**To Reproduce**
1. Go to setting pages.
2. Change the email address to the desired one.
3. Click the confirm button and it will show the success message.
4. Reload the setting page again. Old email reappearing.

**Expected behavior**
Email id should be updated.

**Comment by faiyaz26** [comment]
should be fixed now.
