### ISSUE TITLE
Institution add Request [Sylhet Engineering College]

### ISSUE THREAD

**Issue by Heisenberg71** [lightoj-dev/bugs-and-features#51]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Sylhet Engineering College
2. Website: http://www.sec.ac.bd/
3. Logo Url: https://github.com/lightoj-dev/bugs-and-features/issues/51#issuecomment-762639006
4. Country: Bangladesh

**Comment by faiyaz26** [comment]
Hello, you need to provide an logo? If there is no logo, we can't add the institution. I googled it, nothing came up, in that case create something which I can upload as a logo.

**Comment by Heisenberg71** [comment]
![130930122_1972571389552605_2338665417526188535_n](https://user-images.githubusercontent.com/69238722/104997970-ac55f800-5a54-11eb-972d-3ba9dad7a0e8.jpg)

**Comment by faiyaz26** [comment]
Added: https://lightoj.com/institutions/sec-bd
