### ISSUE TITLE
Institution add Request [IPVCE Luis Urquiza Jorge]

### ISSUE THREAD

**Issue by eblabrada** [lightoj-dev/bugs-and-features#53]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: IPVCE Luis Urquiza Jorge
2. Website: https://twitter.com/Ipvce_LasTunas/
3. Logo Url: https://twitter.com/Ipvce_LasTunas/photo
4. Country: Cuba

**Comment by jan876** [comment]
Done.
