### ISSUE TITLE
Institution add Request [Brahmanbaria Polytechnic Institute]

### ISSUE THREAD

**Issue by Chinm0y** [lightoj-dev/bugs-and-features#54]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Brahmanbaria Polytechnic Institute
2. Website: https://www.bbpi.gov.bd/
3. Logo Url: https://bit.ly/2YQhkfT
4. Country: Bangladesh

**Comment by jan876** [comment]
The logo link is not working. Could you fix it?

**Comment by Chinm0y** [comment]
You can try now.

**Comment by jan876** [comment]
Done.

https://lightoj.com/institutions/bbpi-bd
