### ISSUE TITLE
Problem is not marked for difficulty

### ISSUE THREAD

**Issue by Munmud** [lightoj-dev/bugs-and-features#55]
Under Math -> Number theory ->[loj- 1438](https://lightoj.com/problem/repeated-digit-sum) is not marked for its difficulty.
![asdfasdf](https://user-images.githubusercontent.com/53787290/105500241-d4f81f00-5cec-11eb-89fb-a116e8b6d3fd.PNG)

**Comment by jan876** [comment]
Fixed.
