### ISSUE TITLE
Previously AC code getting TLE

### ISSUE THREAD

**Issue by Metalicana** [lightoj-dev/bugs-and-features#57]
https://lightoj.com/problem/square-queries
this problem

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser information (please complete the following information):**

**Additional context**

**Comment by faiyaz26** [comment]
Please provide the submission link

**Comment by Metalicana** [comment]
https://lightoj.com/submission/1780448

**Comment by Metalicana** [comment]
provided up there ^

**Comment by jan876** [comment]
Looked at the solution. I think this solution should be TLE. The previous dataset was a bit too generous. Uploaded new dataset.

50K queries total. Per query in your code will take n * logn (n = 500, logn = 10). So, overall 5k * 50k, this should get TLE.

Also will rejudge right after.
