### ISSUE TITLE
Institution add Request [CHITTAGONG COLLEGE]

### ISSUE THREAD

**Issue by shawkik** [lightoj-dev/bugs-and-features#59]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: CHITTAGONG COLLEGE
2. Website:https://ctgcollege.gov.bd/
3. Logo Url:https://www.logolynx.com/images/logolynx/77/77a5dced5b43d002ce5496096e056cdb.jpeg
4. Country: BANGLADESH

**Comment by jan876** [comment]
Done
