### ISSUE TITLE
can't sign in successfully

### ISSUE THREAD

**Issue by fahimk495** [lightoj-dev/bugs-and-features#60]
When I try to sign it shows **_Whoops! Got some errors
Please verify your email first before login_**
I tried also doing forgot password. But same thing happens after resetting password.

**Comment by faiyaz26** [comment]
Could you provide your email address or handle you registered on LightOJ website?

**Comment by fahimk495** [comment]
Email: fahim.csedu.bd@gmail.com
Handle: fahimcp495

**Comment by faiyaz26** [comment]
Have you got any email from LightOJ? Please check the spam inbox as well. 

I can see that you have logged in before, but your email is not verified, have you tried to change the email recently?

If you change the email, you should get a verification email.

BTW, you can always login with google login.

**Comment by fahimk495** [comment]
Now it works.
Thank you.

**Comment by faiyaz26** [comment]
Hey, you haven't answered my questions, it would be great if you could answer those which will help us fix bug (if any).

```
Have you got any email from LightOJ? Please check the spam inbox as well.

I can see that you have logged in before, but your email is not verified, have you tried to change the email recently?
```

**Comment by fahimk495** [comment]
Yeah, I have got an email when I tried to change the email address but I didn't verify the email address. Now when I signed in with google and changed my email address with verification, it works well.
