### ISSUE TITLE
Institution add Request [Al-Azhar University]

### ISSUE THREAD

**Issue by AbdeltwabMF** [lightoj-dev/bugs-and-features#61]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Al-Azhar University
2. Website: http://www.azhar.edu.eg/
3. Logo Url: https://azhar.live/wp-content/uploads/2017/05/AL-AZHAR-1.png
4. Country: Egypt

**Comment by jan876** [comment]
Done.

https://lightoj.com/institutions/azhar-eg
