### ISSUE TITLE
Solved count  Problem 

### ISSUE THREAD

**Issue by fahim-ahmed-7861** [lightoj-dev/bugs-and-features#62]
user id : fahim_ahmed_shojib

submission id : 1975785

problem link : https://lightoj.com/problem/square-queries

issue 1)  ager light oj tay 144 prb solve chilo

akn rejudging sesh a 140 dekacche

issue 2) kalkay 6 ta solve korlay 146 howar khota taklay o 145 dekacche

square queries prb ta dekacche 10 month aghe solved

ai prb ta count kortaysena

but 10 month aghe prb ta wa chilo kalkay solve hoice

new solve count kore nai

**Comment by faiyaz26** [comment]
I have just checked, I can confirm we are counting the square queries as solved and counted towards your solve count.

Closing this issue. If you still see similar problem, reopen this or create another one.
