### ISSUE TITLE
Increase the width of the editor to properly read previous submissions.

### ISSUE THREAD

**Issue by PiasRoY** [lightoj-dev/bugs-and-features#64]
**Is your feature request related to a problem? Please describe.**

The size of the editor window in the submission section is not adequate. It is inconvenient to read previous submissions from there. I had to copy that submission to my own editor to read properly.

![loj](https://user-images.githubusercontent.com/36897094/108055105-b716a380-7079-11eb-88cd-ad5d69331cd2.png)

**Describe the solution you'd like**

Just make the editor window full size and move it under the per-file-verdict window.

**Comment by faiyaz26** [comment]
fixed.
