### ISSUE TITLE
LOJ-1133 Problem incomplete statement 

### ISSUE THREAD

**Issue by roslinmahmud** [lightoj-dev/bugs-and-features#66]
What does it mean by 'R' in the input, isn't mentioned in the Problem statement.

**Comment by jan876** [comment]
Are you sure this is the right problem? [LOJ 1133 - Array Simulation](https://lightoj.com/problem/array-simulation), doesn't have any R in input description.

**Comment by jan876** [comment]
Thanks for reporting this, fixed.

**Comment by roslinmahmud** [comment]
> Thanks for reporting this, fixed.

You're most welcome.
