### ISSUE TITLE
Institution add Request [Daffodil Institute of IT]

### ISSUE THREAD

**Issue by asifjoardar** [lightoj-dev/bugs-and-features#67]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Daffodil Institute of IT
2. Website: https://diit.edu.bd/
3. Logo Url: https://diit.edu.bd/static/img/diit_logo.png
4. Country: Bangladesh

**Comment by jan876** [comment]
Done.
