### ISSUE TITLE
Add My Institute

### ISSUE THREAD

**Issue by atiabjobayer** [lightoj-dev/bugs-and-features#68]
Name: National Institute of Technology, Tiruchirappalli
Website: https://nitt.edu
Country: India

![image](https://user-images.githubusercontent.com/14857003/110022187-ceca7900-7d55-11eb-9b44-85df6c866104.png)

**Comment by rahathosen** [comment]
Name: Bangladesh University of Business and Technology (BUBT)
Website: https://bubt.edu.bd/
Country: Bangladesh 
![BUBT-Logo](https://user-images.githubusercontent.com/70264343/110276555-8fbe5100-7ffd-11eb-8f19-c084f32a25b0.png)

**Comment by faiyaz26** [comment]
@atiabjobayer Its added. https://lightoj.com/institutions/nitt-in

**Comment by faiyaz26** [comment]
@rahathosen Two things are wrong with your comment
1. First BUBT is already on LightOJ:  https://lightoj.com/institutions/bubt-bd
2. You are supposed to create an issue on your own, not commenting on another one's.
