### ISSUE TITLE
Institution add Request [Port City International University]

### ISSUE THREAD

**Issue by Mosiur404** [lightoj-dev/bugs-and-features#70]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Port City International University
2. Website: http://www.portcity.edu.bd
3. Logo Url: http://www.portcity.edu.bd/img/Header%20Logo_PCIU-LOGO.png
4. Country: Bangladesh

**Comment by jan876** [comment]
Added.
