### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by mdalarmansorker** [lightoj-dev/bugs-and-features#74]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Bangladesh Army University Of Science And Technology, Saidpur, Nilaphamari
2. Website: https://www.baust.edu.bd/
3. Logo Url: https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBangladesh_Army_University_of_Science_and_Technology&psig=AOvVaw2HWmgCwQDn11G0SRe1HGng&ust=1616050479296000&source=images&cd=vfe&ved=0CA0QjhxqFwoTCMDi0afftu8CFQAAAAAdAAAAABAD
4. Country: Bangladesh

**Comment by byrthokobi** [comment]
Institution name: University of Rajshahi
Website: ru.ac.bd
Logo url: https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FUniversity_of_Rajshahi&psig=AOvVaw0F-hccWyGX5VHe6wevnirn&ust=1616137808124000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIiBh9Okue8CFQAAAAAdAAAAABAO
Country: Bangladesh

**Comment by faiyaz26** [comment]
@byrthokobi you should create another issue rather than commenting here. BTW, the issue was search was not working. Both of the institute already exists.

https://lightoj.com/institutions/ru-bd

https://lightoj.com/institutions/baiust-bd
