### ISSUE TITLE
Institution add Request [ PSG College Of Technology]

### ISSUE THREAD

**Issue by AarhonJoshuaa** [lightoj-dev/bugs-and-features#79]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: PSG College Of Technology
2. Website: https://www.psgtech.edu/
3. Logo Url: https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/PSG_College_of_Technology_logo.png/220px-PSG_College_of_Technology_logo.png
4. Country: India

**Comment by jan876** [comment]
Added.
