### ISSUE TITLE
Can't Login with Previous Email

### ISSUE THREAD

**Issue by Double-O** [lightoj-dev/bugs-and-features#8]
I tried my previous email and password but it showed errors. So I tried forgot password option but it said there is no account with my email address. Have you removed all the old IDs?

My email address : hrdd03@gmail.com

**Comment by jan876** [comment]
Thanks for reporting this. There was a small bug and your account was added with uppercase email address for some reason. Fixed it.

Please close the issue if you are able to log in.

**Comment by faiyaz26** [comment]
Reopen, if its not fixed.
