### ISSUE TITLE
Institution add Request [Rajbari Govt. High School]

### ISSUE THREAD

**Issue by rinikapaul84** [lightoj-dev/bugs-and-features#81]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Rajbari Govt. High School, Rajbari
2. Website:
3. Logo Url: 
![rghs](https://user-images.githubusercontent.com/65020283/113511127-15430b80-9580-11eb-864e-4b56383ec0a4.jpg)

4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/rajbarighs-bd
