### ISSUE TITLE
Solved questions counter not incrementing

### ISSUE THREAD

**Issue by weastel** [lightoj-dev/bugs-and-features#83]
**Describe the bug**

**To Reproduce**
1. Solve an unsolved question
2. Not able to see increased counter for solved question. 

**Expected behavior**
Counter for solved questions should increase not instantaneously but should increase. I solved 2-3 questions still counter shows my previous solved number. 

**Screenshots**
![Screenshot from 2021-04-05 02-07-59](https://user-images.githubusercontent.com/42701709/113520914-ca42eb80-95b3-11eb-916a-023afcb9b7eb.png)

**Browser information (please complete the following information):**
 - OS: Fedora 33
 - Browser: Chrome

**Comment by faiyaz26** [comment]
Fixed.
