### ISSUE TITLE
Institution add Request [Rangpur Engineering College, Rangpur]

### ISSUE THREAD

**Issue by iamnoyon** [lightoj-dev/bugs-and-features#84]
Institution Name: Rangpur Engineering College, Rangpur
Website Link: http://www.recr.edu.bd/
![Rangpur Engineering College, Rangpur](https://user-images.githubusercontent.com/31146513/113726645-389fbf00-9716-11eb-9af1-3cd5edacabbe.jpg)
Country: Bangladesh

**Comment by jan876** [comment]
Added.
