### ISSUE TITLE
Institution add Request [Khulna Zilla School,Khulna]

### ISSUE THREAD

**Issue by srlabib** [lightoj-dev/bugs-and-features#85]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Khulna Zilla School,Khulna
2. Website: http://kzs.edu.bd/
3. Logo Url: https://user-images.githubusercontent.com/71954819/114173872-a38d0800-9959-11eb-9262-6b948860270a.png

4. Country: Bangladesh

**Comment by jan876** [comment]
Done.
