### ISSUE TITLE
Code Editor problem in dark mode

### ISSUE THREAD

**Issue by raselhasan11** [lightoj-dev/bugs-and-features#86]
**Describe the bug**
When using code editor in dark mode, I select some portion of code, it highlights that portion of code nicely, but when I select full code by Ctrl + A, it selects full code but, it's not visual, I mean I see like nothing is selected. 
Can you please make a good color combination for this in dark mode.

![Commandos _ Ligh (1)](https://user-images.githubusercontent.com/62126649/114824867-47a60180-9de7-11eb-916e-6a18d58af343.png)
![Commandos _ Ligh](https://user-images.githubusercontent.com/62126649/114824880-4d034c00-9de7-11eb-9981-57cdf6d8ea2f.png)

Screeshots are attached.

**Comment by jan876** [comment]
we have switched to Monaco Editor. This should be fixed. Please close this ticket if resolved.
