### ISSUE TITLE
Institution add Request [Ahsanullah Institute of Information & Communication Technology]

### ISSUE THREAD

**Issue by tahmidarefin** [lightoj-dev/bugs-and-features#89]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Ahsanullah Institute of Information & Communication Technology
2. Website: http://aiict.edu.bd/
3. Logo Url: http://aiict.edu.bd/wp-content/themes/child-simple-east/images/logo.png
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/aiict-bd
