### ISSUE TITLE
Please add my institution

### ISSUE THREAD

**Issue by zubair-ahmed0-0** [lightoj-dev/bugs-and-features#92]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name:BAF Shaheen College Dhaka
2. Website:https://www.bafsd.edu.bd/
3. Logo Url:
![image](https://user-images.githubusercontent.com/82076434/120883174-83965f80-c5fd-11eb-8f8c-9f710e4a612b.png)

4. Country:Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/bafsd-bd
