### ISSUE TITLE
JATIR PITA BANGABANDHU GOVT. COLLEGE

### ISSUE THREAD

**Issue by Robin2561** [lightoj-dev/bugs-and-features#93]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: JATIR PITA BANGABANDHU GOVT. COLLEGE
2. Website:http://www.jpbgc.edu.bd/
3. Logo Url:https://neticms.com/institute/home
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/jpbgc-bd
