### ISSUE TITLE
Institution add Request [Institute of Science Trade & Technology]

### ISSUE THREAD

**Issue by dabananda** [lightoj-dev/bugs-and-features#94]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Institute of Science Trade & Technology
2. Website: https://www.istt.edu.bd/
3. Logo Url: https://drive.google.com/file/d/1ypbDF-OrZUiWC7QhL9oMUAIH46I0Ax-b/view?usp=sharing
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/istt-bd
