### ISSUE TITLE
Institution add Request [Institution Name]

### ISSUE THREAD

**Issue by MahirDaiyanSafwaan3399** [lightoj-dev/bugs-and-features#95]
Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Dhaka Residential Model College
2. Website: http://www.drmc.edu.bd/
3. Logo Url:
4. Country: Bangladesh

**Comment by jan876** [comment]
https://lightoj.com/institutions/drmc-bd
