### ISSUE TITLE
Institution add Request [Shri Govindram Seksaria Institute of Technology and Science (SGSITS)]

### ISSUE THREAD

**Issue by Git-Harshit** [lightoj-dev/bugs-and-features#96]
- [x] Please make sure there is no other related issue about this institution add request.

Please provide the information below:

1. Institution Name: Shri Govindram Seksaria Institute of Technology and Science (SGSITS)
2. Website: [https://sgsits.ac.in/](https://sgsits.ac.in/)
3. Logo Url: [https://sgsits.ac.in/images/3_sgsits_logo.png](https://sgsits.ac.in/images/3_sgsits_logo.png)
4. Country: India
5. State: Madhya Pradesh (M. P.)
6. City: Indore

The basic institutional information is provided as per your Institute add request issue format. I belong to the mentioned institute, so please feel free to comment below for any more informational requirements. I am looking forward to getting my institute added to LightOJ soon so that I and my college mates can update it on their profiles as needed.

**Comment by jan876** [comment]
https://lightoj.com/institutions/sgsits-in
