### ISSUE TITLE
Problem in Outh_token while sign-up with github

### ISSUE THREAD

**Issue by 0x7EVEN** [lightoj-dev/bugs-and-features#97]
**Screenshots**
![image](https://user-images.githubusercontent.com/76391543/125924866-dd0fd720-cc65-47c7-86da-1a29637f7600.png)
.

**Browser information (please complete the following information):**
 - OS: win10
 - Browser.: chrome,

**Additional context**

**Comment by faiyaz26** [comment]
Hello,
I tried to reproduce it, unfortunately can't reproduce. Have you tried multiple times?
