### ISSUE TITLE
Problem statement correction

### ISSUE THREAD

**Issue by raselhasan11** [lightoj-dev/bugs-and-features#98]
![Sigma Function _](https://user-images.githubusercontent.com/62126649/127033361-5a0de218-2e3d-45aa-b601-bbc65c32b35e.png)
It should be Pk instead of P1.

**Comment by faiyaz26** [comment]
Could you share the problem link?

**Comment by raselhasan11** [comment]
> Could you share the problem link?

https://lightoj.com/problem/sigma-function

**Comment by faiyaz26** [comment]
fixed.
